In [1]:
import numpy as np
import pandas as pd

In [2]:
Data = pd.read_csv("m6A_QTL_Allsite.csv")

In [3]:
Data

,chrom,SNPID,strand,PeakStart,PeakEnd,name,Peak,POS,REF,ALT,txStart,txEnd,cdsStart,cdsEnd,LastExonStart,LastExonEnd
0,chr20,rs3746661,+,3846845,3847244,MAVS,chr20:3846845-3847244_MAVS_+,3847142,G,C,3827489,3849280,3835271,3846794,3846329,3849280
1,chr20,rs3746662,+,3847294,3847393,MAVS,chr20:3847294-3847393_MAVS_+,3847325,A,C,3827489,3849280,3835271,3846794,3846329,3849280
2,chr20,rs4616,-,33590306,33591323,TRPC4AP,chr20:33590306-33591323_TRPC4AP_-,33590358,C,T,33590206,33680610,33590948,33680584,33590206,33591086
3,chr20,rs5856,+,2637782,2638989,NOP56,chr20:2637782-2638989_NOP56_+,2638882,T,C,2632790,2639039,2633306,2638940,2638574,2639039
4,chr20,rs6753,+,2637782,2638989,NOP56,chr20:2637782-2638989_NOP56_+,2638579,T,C,2632790,2639039,2633306,2638940,2638574,2639039
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89886,chr18,rs10164140,+,47919599,47919895,SKA1,chr18:47919599-47919895_SKA1_+,47919635,G,A,47901364,47920543,47902200,47918617,47918468,47920543
89887,chr18,rs16951872,+,47918511,47918610,SKA1,chr18:47918511-47918610_SKA1_+,47918536,C,T,47901364,47920543,47902200,47918617,47918468,47920543
89888,chr18,rs17072097,+,61582745,61582794,SERPINB10,chr18:61582745-61582794_SERPINB10_+,61582751,T,G,61575224,61603345,61582744,61602476,61602071,61603345
89889,chr18,rs34402690,-,5290657,5291650,ZBTB14,chr18:5290657-5291650_ZBTB14_-,5291304,C,T,5289017,5296039,5290856,5293245,5289017,5292203
89890,chr18,rs35287972,+,77896284,77896632,ADNP2,chr18:77896284-77896632_ADNP2_+,77896308,A,G,77866914,77898234,77875425,77896692,77893494,77898234

In [4]:
Table = Data[["SNPID","Peak"]]

### Get values for m6A Peak

In [5]:
m6A = pd.read_csv("m6APeak_logOR_GC.IP.adjusted_qqnorm.fastQTL.csv")
m6A.drop(["chr","start","end"], axis=1, inplace=True)
m6A.rename(columns={"PEAK":"Peak"}, inplace = True)

In [6]:
m6A = pd.merge(Table, m6A, how="inner", on=["Peak"])

In [7]:
m6A

,SNPID,Peak,NA18486,NA18498,NA18499,NA18501,NA18502,NA18504,NA18505,NA18507,...,NA19159,NA19160,NA19192,NA19193,NA19200,NA19204,NA19209,NA19222,NA19239,NA19257
0,rs3746661,chr20:3846845-3847244_MAVS_+,-0.578796,-1.341600,-0.411813,-1.664600,-0.522673,0.013969,0.438269,-2.224451,...,1.157707,0.426533,-0.009596,1.510635,-0.224762,2.384439,-0.849244,-0.517389,1.681336,-1.159133
1,rs3746662,chr20:3847294-3847393_MAVS_+,0.440945,0.960848,-0.279942,-2.916720,-2.100185,1.252071,-1.581658,-1.183982,...,0.581814,0.835217,-0.143820,0.423741,0.857109,0.979909,0.026482,0.207976,-0.910971,0.352096
2,rs4616,chr20:33590306-33591323_TRPC4AP_-,0.155981,1.065563,0.999133,0.048361,-0.392585,-0.554833,-0.621997,0.743164,...,-0.261672,-0.802438,-1.646901,-1.271729,1.852777,-0.828693,1.068353,0.054686,0.018220,-0.100009
3,rs5856,chr20:2637782-2638989_NOP56_+,-0.344739,1.139152,1.908280,-1.786655,-1.551010,-1.456959,-1.073526,-0.326492,...,-0.227628,-1.097166,0.717787,-0.413929,1.203048,0.542409,0.658677,0.845418,-0.313963,0.759432
4,rs6753,chr20:2637782-2638989_NOP56_+,-0.344739,1.139152,1.908280,-1.786655,-1.551010,-1.456959,-1.073526,-0.326492,...,-0.227628,-1.097166,0.717787,-0.413929,1.203048,0.542409,0.658677,0.845418,-0.313963,0.759432
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89886,rs10164140,chr18:47919599-47919895_SKA1_+,-0.701538,-0.448320,0.708390,0.679033,0.790263,1.172553,-0.456123,-0.124945,...,2.598906,-0.168288,0.618169,-1.264401,0.262300,0.999133,-0.947254,0.670492,-0.434395,0.983252
89887,rs16951872,chr18:47918511-47918610_SKA1_+,-1.944791,-0.411680,-1.254735,2.020142,-0.434529,-1.134285,0.083542,0.908767,...,-0.442150,0.841777,-0.201403,-0.073673,0.116870,0.104649,-0.500659,-1.015473,-0.196076,0.267961
89888,rs17072097,chr18:61582745-61582794_SERPINB10_+,-0.598003,-0.410887,-0.454102,0.355070,-0.087199,-0.374804,0.387473,0.966452,...,0.333418,-1.861636,0.157088,-0.092199,0.258028,0.161147,0.747815,0.097812,-0.253510,-1.144981
89889,rs34402690,chr18:5290657-5291650_ZBTB14_-,0.743164,-0.636804,-0.551154,0.128251,-0.096225,-0.502863,0.370898,0.079520,...,0.780013,-1.113048,0.478341,-0.860446,0.397969,1.622414,-0.276028,1.043327,1.140548,0.717316
89890,rs35287972,chr18:77896284-77896632_ADNP2_+,0.238862,-0.766745,0.068437,-0.256522,-0.083664,-0.160163,-0.147749,-0.018706,...,0.983252,-1.913558,-0.359861,-0.176055,0.149714,-0.904919,-0.617875,0.606011,-0.106114,1.459773

### SNP info

In [8]:
SNP = pd.read_table("SNP.txt", sep="\t", low_memory=False)
SNP.rename(columns={"#CHROM":"chrom", "ID":"SNPID"}, inplace = True)
SNP.drop(["chrom","POS","REF","ALT","QUAL","FILTER","INFO","FORMAT"], axis=1, inplace=True)

In [9]:
SNP

,SNPID,NA18486,NA18498,NA18499,NA18501,NA18502,NA18504,NA18505,NA18507,NA18508,...,NA19159,NA19160,NA19192,NA19193,NA19200,NA19204,NA19209,NA19222,NA19239,NA19257
0,rs199926908,1|1,1|1,1|1,1|0,1|1,0|0,0|0,0|0,0|0,...,1|1,1|0,0|1,1|1,0|0,1|1,0|0,1|1,1|1,1|1
1,rs369001800,1|1,1|1,1|1,1|0,1|1,0|0,0|0,0|0,0|0,...,1|1,1|0,0|1,1|1,0|0,1|1,0|0,1|1,1|1,1|1
2,rs61838970,1|1,0|0,1|1,0|0,1|1,0|0,0|0,0|0,0|0,...,1|1,1|0,0|1,1|1,0|0,1|1,0|0,1|1,1|1,1|1
3,rs536515158,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|1,0|0,0|0
4,rs61838971,1|1,1|1,1|1,1|0,1|1,0|0,0|0,0|0,0|0,...,1|1,1|0,0|1,1|1,0|0,1|1,0|0,1|1,1|1,1|1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10200254,.,1|0,0|0,0|0,0|0,1|0,0|0,1|0,1|0,0|0,...,1|0,1|0,0|0,0|0,0|0,1|1,0|1,0|0,0|1,1|0
10200255,.,0|0,1|0,1|0,0|0,1|0,0|0,0|0,0|1,0|0,...,1|1,1|0,0|0,0|0,0|1,0|0,1|0,0|0,0|1,0|1
10200256,.,1|1,1|1,1|1,0|1,1|0,1|1,1|1,1|1,1|1,...,1|0,0|1,1|1,1|1,1|0,1|0,0|1,0|1,1|0,1|0
10200257,.,1|0,1|1,1|0,0|0,1|0,1|0,0|0,1|1,0|0,...,1|1,0|1,0|1,0|1,0|1,1|0,1|1,1|1,1|1,1|1
10200258,.,0|0,0|0,0|1,0|1,0|0,0|0,1|1,0|1,0|0,...,0|1,0|1,1|0,0|0,0|0,0|1,1|1,0|0,0|1,0|0

In [10]:
SNP = pd.merge(Table, SNP, how="inner", on=["SNPID"])

In [11]:
SNP.replace("1|1", 1, inplace=True)
SNP.replace("1|0", 0.5, inplace=True)
SNP.replace("0|1", 0.5, inplace=True)
SNP.replace("0|0", 0, inplace=True)

In [12]:
SNP

,SNPID,Peak,NA18486,NA18498,NA18499,NA18501,NA18502,NA18504,NA18505,NA18507,...,NA19159,NA19160,NA19192,NA19193,NA19200,NA19204,NA19209,NA19222,NA19239,NA19257
0,rs3746661,chr20:3846845-3847244_MAVS_+,0.5,0.5,0.0,0,0.5,0,0.5,0,...,0.5,0,0,0.5,0,0.0,0.0,0.0,1,0.0
1,rs3746662,chr20:3847294-3847393_MAVS_+,0.5,0.5,0.0,0.5,0.0,0.5,0.0,0.5,...,0.5,0.5,0.5,0.0,0.5,1.0,1.0,0.5,0,0.5
2,rs4616,chr20:33590306-33591323_TRPC4AP_-,0,0.5,0.0,0,0.0,0,0.0,0,...,0.0,0,0,0.0,0,0.0,0.0,0.0,0,0.0
3,rs5856,chr20:2637782-2638989_NOP56_+,0.5,0.5,0.5,0.5,0.5,1,1.0,0.5,...,0.0,0.5,1,0.5,0.5,1.0,0.5,0.5,1,0.5
4,rs6753,chr20:2637782-2638989_NOP56_+,0.5,0.5,0.5,0.5,0.5,1,1.0,0.5,...,0.0,0.5,1,0.5,0.5,1.0,0.5,0.5,1,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89886,rs10164140,chr18:47919599-47919895_SKA1_+,0,0.5,0.5,0.5,0.5,0.5,0.5,0,...,1.0,0,0,0.0,0,0.0,0.0,0.0,1,0.0
89887,rs16951872,chr18:47918511-47918610_SKA1_+,0,0.5,0.5,0.5,0.5,0.5,0.5,0,...,1.0,0,0,0.0,0,0.0,0.0,0.0,1,0.0
89888,rs17072097,chr18:61582745-61582794_SERPINB10_+,0,0.5,0.0,0.5,0.5,0,0.5,0.5,...,0.5,0,1,0.0,1,0.0,0.5,0.0,0,0.5
89889,rs34402690,chr18:5290657-5291650_ZBTB14_-,0,0.5,0.5,0,0.0,0,0.5,0.5,...,0.0,0.5,0,0.5,0,0.0,0.0,0.0,0,0.0
89890,rs35287972,chr18:77896284-77896632_ADNP2_+,0.5,0,0.0,0.5,0.5,0.5,0.0,0,...,0.0,0,0.5,0.0,0,0.0,0.0,0.0,0,0.0

In [22]:
    Score = pd.DataFrame(np.array(SNP.iloc[1,2:62]), columns=["Score"])
    Value = pd.DataFrame(np.array(m6A.iloc[1,2:62]), columns=["Value"])
    data = pd.merge(Score, Value, left_index=True, right_index=True)
    
    x = np.asarray(data["Score"], dtype=float)
    y = np.asarray(data["Value"], dtype=float)
    x = sm.add_constant(x)
    model = sm.OLS(y, x).fit()

In [23]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                 -0.017
Method:                 Least Squares   F-statistic:                   0.01960
Date:                Tue, 16 Feb 2021   Prob (F-statistic):              0.889
Time:                        02:04:38   Log-Likelihood:                -85.904
No. Observations:                  60   AIC:                             175.8
Df Residuals:                      58   BIC:                             180.0
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.0355      0.226     -0.158      0.875      -0.487       0.416
x1             0.0510      0.364      0.140      0.889      -0.678       0.780
==============================================================================
Omnibus:                        5.226   Durbin-Watson:                   1.480
Prob(Omnibus):                  0.073   Jarque-Bera (JB):                4.466
Skew:                          -0.654   Prob(JB):                        0.107
Kurtosis:                       3.273   Cond. No.                         3.50
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [24]:
model.params

array([-0.03552171,  0.05099073])

In [13]:
import statsmodels.api as sm

In [26]:
Intercept = []
Slope = []
Std = []
R2 = []
R2adj = []
Pvalue = []
T = []
F = []
Fpvalue = []
AIC = []
BIC = []

for i in range(len(m6A)):
    Score = pd.DataFrame(np.array(SNP.iloc[i,2:62]), columns=["Score"])
    Value = pd.DataFrame(np.array(m6A.iloc[i,2:62]), columns=["Value"])
    data = pd.merge(Score, Value, left_index=True, right_index=True)
    
    x = np.asarray(data["Score"], dtype=float)
    y = np.asarray(data["Value"], dtype=float)
    x = sm.add_constant(x)
    model = sm.OLS(y, x).fit()
    
    r2 = model.rsquared
    adj = model.rsquared_adj
    
    intercept = model.params[0]
    slope = model.params[1]
    
    t = model.tvalues[0]
    pvalue = model.pvalues[1]
    std = model.bse[0]
    f = model.fvalue
    fpvalue = model.f_pvalue
    aic=model.aic
    bic= model.bic
    
    Slope.append(slope)
    Intercept.append(intercept)
    R2.append(r2)
    R2adj.append(adj)
    Pvalue.append(pvalue)
    Std.append(std)
    T.append(t)
    F.append(f)
    Fpvalue.append(fpvalue)
    AIC.append(aic)
    BIC.append(bic)

In [27]:
List = [Slope, Intercept,T, R2, R2adj, Pvalue, Std, F, Fpvalue, AIC, BIC]
df = pd.DataFrame(List)
df = df.T
df.rename(columns={0:"Slope", 1:"Intercept",2:"T", 3:"R2", 4:"R2_adj", 5:"Pvalue", 6:"Std", 7:"F", 8:"Fpvalue", 9:"AIC", 10:"BIC"}, inplace = True)
df

,Slope,Intercept,T,R2,R2_adj,Pvalue,Std,F,Fpvalue,AIC,BIC
0,1.028121,-0.149888,-1.024243,0.069303,0.053256,0.309973,0.146340,4.318883,0.042127,171.647884,175.836573
1,0.050991,-0.035522,-0.157520,0.000338,-0.016898,0.875382,0.225506,0.019599,0.889147,175.807100,179.995789
2,0.556342,-0.050502,-0.337404,0.006900,-0.010223,0.737030,0.149678,0.402952,0.528065,182.543901,186.732590
3,-0.586577,0.378250,1.353810,0.038366,0.021786,0.181049,0.279397,2.314019,0.133646,166.872371,171.061060
4,-0.586577,0.378250,1.353810,0.038366,0.021786,0.181049,0.279397,2.314019,0.133646,166.872371,171.061060
...,...,...,...,...,...,...,...,...,...,...,...
89886,1.209426,-0.349462,-2.216000,0.168617,0.154282,0.030629,0.157700,11.763246,0.001119,165.463086,169.651775
89887,-0.715629,0.200146,1.170323,0.058059,0.041819,0.246657,0.171018,3.575000,0.063654,173.641109,177.829798
89888,-0.064289,0.024534,0.129252,0.000470,-0.016764,0.897605,0.189812,0.027245,0.869470,171.816972,176.005661
89889,-1.486414,0.171851,1.317661,0.100700,0.085195,0.192798,0.130421,6.494610,0.013490,160.072302,164.260992
89890,0.700487,-0.082351,-0.559263,0.020697,0.003813,0.578136,0.147249,1.225814,0.272793,173.372101,177.560790

In [28]:
Table = SNP[["SNPID", "Peak"]]

In [29]:
Table = pd.merge(Table, df, left_index=True, right_index=True)

In [30]:
Table

,SNPID,Peak,Slope,Intercept,T,R2,R2_adj,Pvalue,Std,F,Fpvalue,AIC,BIC
0,rs3746661,chr20:3846845-3847244_MAVS_+,1.028121,-0.149888,-1.024243,0.069303,0.053256,0.309973,0.146340,4.318883,0.042127,171.647884,175.836573
1,rs3746662,chr20:3847294-3847393_MAVS_+,0.050991,-0.035522,-0.157520,0.000338,-0.016898,0.875382,0.225506,0.019599,0.889147,175.807100,179.995789
2,rs4616,chr20:33590306-33591323_TRPC4AP_-,0.556342,-0.050502,-0.337404,0.006900,-0.010223,0.737030,0.149678,0.402952,0.528065,182.543901,186.732590
3,rs5856,chr20:2637782-2638989_NOP56_+,-0.586577,0.378250,1.353810,0.038366,0.021786,0.181049,0.279397,2.314019,0.133646,166.872371,171.061060
4,rs6753,chr20:2637782-2638989_NOP56_+,-0.586577,0.378250,1.353810,0.038366,0.021786,0.181049,0.279397,2.314019,0.133646,166.872371,171.061060
...,...,...,...,...,...,...,...,...,...,...,...,...,...
89886,rs10164140,chr18:47919599-47919895_SKA1_+,1.209426,-0.349462,-2.216000,0.168617,0.154282,0.030629,0.157700,11.763246,0.001119,165.463086,169.651775
89887,rs16951872,chr18:47918511-47918610_SKA1_+,-0.715629,0.200146,1.170323,0.058059,0.041819,0.246657,0.171018,3.575000,0.063654,173.641109,177.829798
89888,rs17072097,chr18:61582745-61582794_SERPINB10_+,-0.064289,0.024534,0.129252,0.000470,-0.016764,0.897605,0.189812,0.027245,0.869470,171.816972,176.005661
89889,rs34402690,chr18:5290657-5291650_ZBTB14_-,-1.486414,0.171851,1.317661,0.100700,0.085195,0.192798,0.130421,6.494610,0.013490,160.072302,164.260992
89890,rs35287972,chr18:77896284-77896632_ADNP2_+,0.700487,-0.082351,-0.559263,0.020697,0.003813,0.578136,0.147249,1.225814,0.272793,173.372101,177.560790

In [31]:
Table = Table[Table["Pvalue"]<=0.1]
Table = Table.reset_index(drop = True)

In [32]:
Table

,SNPID,Peak,Slope,Intercept,T,R2,R2_adj,Pvalue,Std,F,Fpvalue,AIC,BIC
0,rs3182973,chr20:57569747-57570139_NELFCD_+,2.667875,-0.216950,-1.733018,0.246006,0.233006,0.088407,0.125186,18.923667,0.000056,157.605754,161.794443
1,rs7397,chr20:61431004-61431648_MRGBP_+,0.746663,-0.433697,-1.679211,0.060896,0.044704,0.098491,0.258274,3.760971,0.057331,170.773432,174.962121
2,rs8567,chr20:62522205-62522403_TPD52L2_+,1.026886,-0.458728,-2.242772,0.120971,0.105815,0.028748,0.204536,7.981893,0.006469,166.246647,170.435336
3,rs238187,chr20:47887351-47892424_ZNFX1_-,1.136844,-0.595244,-3.155597,0.193589,0.179685,0.002540,0.188631,13.923582,0.000435,154.380746,158.569436
4,rs238188,chr20:47887351-47892424_ZNFX1_-,1.136844,-0.595244,-3.155597,0.193589,0.179685,0.002540,0.188631,13.923582,0.000435,154.380746,158.569436
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3292,rs8084109,chr18:72167153-72168646_CNDP2_+,-1.348009,0.715976,3.648466,0.255047,0.242203,0.000567,0.196240,19.857250,0.000039,158.645369,162.834058
3293,rs8084410,chr18:72167153-72168646_CNDP2_+,-1.249424,0.685043,3.417894,0.230004,0.216728,0.001160,0.200428,17.325029,0.000106,160.629242,164.817931
3294,rs12605820,chr18:72167153-72168646_CNDP2_+,-1.825938,0.434324,3.009475,0.281088,0.268693,0.003869,0.144319,22.677441,0.000013,156.510451,160.699140
3295,rs10164137,chr18:47919599-47919895_SKA1_+,1.156638,-0.353783,-2.209783,0.163164,0.148736,0.031081,0.160099,11.308684,0.001371,165.855312,170.044001
3296,rs10164140,chr18:47919599-47919895_SKA1_+,1.209426,-0.349462,-2.216000,0.168617,0.154282,0.030629,0.157700,11.763246,0.001119,165.463086,169.651775

In [33]:
Table.to_csv("LinearRegression.csv",index=0)

In [22]:
Table = Table[["SNPID","Peak"]]

In [23]:
Data = pd.merge(Data, Table, how="inner", on=["SNPID","Peak"])

In [24]:
Data

,chrom,SNPID,strand,PeakStart,PeakEnd,name,Peak,POS,REF,ALT,txStart,txEnd,cdsStart,cdsEnd,LastExonStart,LastExonEnd
0,chr20,rs3182973,+,57569747,57570139,NELFCD,chr20:57569747-57570139_NELFCD_+,57569938,A,G,57556262,57570188,57556310,57569731,57569696,57570188
1,chr20,rs7397,+,61431004,61431648,MRGBP,chr20:61431004-61431648_MRGBP_+,61431557,A,C,61427804,61431945,61427875,61430995,61430807,61431945
2,chr20,rs8567,+,62522205,62522403,TPD52L2,chr20:62522205-62522403_TPD52L2_+,62522315,A,G,62496642,62522898,62496718,62521298,62521202,62522898
3,chr20,rs238187,-,47887351,47892424,ZNFX1,chr20:47887351-47892424_ZNFX1_-,47890342,T,C,47862436,47894756,47863803,47892376,47862436,47866248
4,chr20,rs238188,-,47887351,47892424,ZNFX1,chr20:47887351-47892424_ZNFX1_-,47891332,G,C,47862436,47894756,47863803,47892376,47862436,47866248
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3292,chr18,rs8084109,+,72167153,72168646,CNDP2,chr18:72167153-72168646_CNDP2_+,72168312,T,A,72163442,72188363,72167208,72187303,72187233,72188363
3293,chr18,rs8084410,+,72167153,72168646,CNDP2,chr18:72167153-72168646_CNDP2_+,72168486,T,C,72163442,72188363,72167208,72187303,72187233,72188363
3294,chr18,rs12605820,+,72167153,72168646,CNDP2,chr18:72167153-72168646_CNDP2_+,72167802,G,A,72163442,72188363,72167208,72187303,72187233,72188363
3295,chr18,rs10164137,+,47919599,47919895,SKA1,chr18:47919599-47919895_SKA1_+,47919736,C,A,47901364,47920543,47902200,47918617,47918468,47920543
3296,chr18,rs10164140,+,47919599,47919895,SKA1,chr18:47919599-47919895_SKA1_+,47919635,G,A,47901364,47920543,47902200,47918617,47918468,47920543

In [25]:
Bed = Data.iloc[:, [0, 10, 11]]

In [26]:
Bed

      chrom   txStart     txEnd
0     chr20  57556262  57570188
1     chr20  61427804  61431945
2     chr20  62496642  62522898
3     chr20  47862436  47894756
4     chr20  47862436  47894756
...     ...       ...       ...
3292  chr18  72163442  72188363
3293  chr18  72163442  72188363
3294  chr18  72163442  72188363
3295  chr18  47901364  47920543
3296  chr18  47901364  47920543

[3297 rows x 3 columns]

In [27]:
Bed.to_csv("m6A_QTL_SigSite.bed", sep="\t", header=False, index=False)

In [28]:
!bedtools getfasta -bed m6A_QTL_SigSite.bed -fi /pod/2/ke-lab/LUOZ/Reference/Fasta/hg19/hg19.fa -fo m6A_QTL_SigSite.txt

In [29]:
from Bio import SeqIO
from Bio.Seq import Seq

In [30]:
meta=[]
sequence=[]
seq = ('m6A_QTL_SigSite.txt')

In [31]:
for seq_record in SeqIO.parse(seq, "fasta"):
    meta.append(str(seq_record.id))
    sequence.append(str(seq_record.seq))

In [32]:
Fasta = pd.DataFrame(data ={'Meta':meta,'Sequence':sequence})
Result = pd.merge(Data, Fasta, left_index=True, right_index=True, how='outer')

In [33]:
Result.drop(["Meta"], axis=1, inplace=True)
Result["GeneLength"] = Result["txEnd"] - Result["txStart"]

In [34]:
Result

,chrom,SNPID,strand,PeakStart,PeakEnd,name,Peak,POS,REF,ALT,txStart,txEnd,cdsStart,cdsEnd,LastExonStart,LastExonEnd,Sequence,GeneLength
0,chr20,rs3182973,+,57569747,57570139,NELFCD,chr20:57569747-57570139_NELFCD_+,57569938,A,G,57556262,57570188,57556310,57569731,57569696,57570188,gaggcgcgcggccgcgcgtgcgcccgcccgcccgtccccgcctcgc...,13926
1,chr20,rs7397,+,61431004,61431648,MRGBP,chr20:61431004-61431648_MRGBP_+,61431557,A,C,61427804,61431945,61427875,61430995,61430807,61431945,AGTGCGCCTGCGCGGAGCTCGTGGCCGCGCCTGCTCCCGCCGGGGG...,4141
2,chr20,rs8567,+,62522205,62522403,TPD52L2,chr20:62522205-62522403_TPD52L2_+,62522315,A,G,62496642,62522898,62496718,62521298,62521202,62522898,ACGCGGCGAGCTTCTCCCGGCGCCGCCCGCTCGGCTCCCATAGCGC...,26256
3,chr20,rs238187,-,47887351,47892424,ZNFX1,chr20:47887351-47892424_ZNFX1_-,47890342,T,C,47862436,47894756,47863803,47892376,47862436,47866248,TTTTCTCAATCATTGTTTTTAATTGGCTTTATAAGCTAAAGTGCAT...,32320
4,chr20,rs238188,-,47887351,47892424,ZNFX1,chr20:47887351-47892424_ZNFX1_-,47891332,G,C,47862436,47894756,47863803,47892376,47862436,47866248,TTTTCTCAATCATTGTTTTTAATTGGCTTTATAAGCTAAAGTGCAT...,32320
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3292,chr18,rs8084109,+,72167153,72168646,CNDP2,chr18:72167153-72168646_CNDP2_+,72168312,T,A,72163442,72188363,72167208,72187303,72187233,72188363,GAAATGGGGCGGGGAGAGAGTGACACCACCCCTCTGCCTGTGGCTG...,24921
3293,chr18,rs8084410,+,72167153,72168646,CNDP2,chr18:72167153-72168646_CNDP2_+,72168486,T,C,72163442,72188363,72167208,72187303,72187233,72188363,GAAATGGGGCGGGGAGAGAGTGACACCACCCCTCTGCCTGTGGCTG...,24921
3294,chr18,rs12605820,+,72167153,72168646,CNDP2,chr18:72167153-72168646_CNDP2_+,72167802,G,A,72163442,72188363,72167208,72187303,72187233,72188363,GAAATGGGGCGGGGAGAGAGTGACACCACCCCTCTGCCTGTGGCTG...,24921
3295,chr18,rs10164137,+,47919599,47919895,SKA1,chr18:47919599-47919895_SKA1_+,47919736,C,A,47901364,47920543,47902200,47918617,47918468,47920543,GATGACGCAAACCGGGAACAGCGGCTGAGCCTGCGCTTCGGAAGCA...,19179
3296,chr18,rs10164140,+,47919599,47919895,SKA1,chr18:47919599-47919895_SKA1_+,47919635,G,A,47901364,47920543,47902200,47918617,47918468,47920543,GATGACGCAAACCGGGAACAGCGGCTGAGCCTGCGCTTCGGAAGCA...,19179

In [35]:
Data = Result

In [36]:
Positive = Data[Data["strand"]=="+"]
Positive = Positive.reset_index(drop = True)
Negative = Data[Data["strand"]=="-"]
Negative = Negative.reset_index(drop = True)

In [37]:
Positive["SNPposition"] = Positive["POS"] - Positive["txStart"]
Negative["SNPposition"] = Negative["txEnd"] - Negative["POS"]+1

In [38]:
Data = Positive.append(Negative)
Data = Data.reset_index(drop = True)

In [39]:
Data

,chrom,SNPID,strand,PeakStart,PeakEnd,name,Peak,POS,REF,ALT,txStart,txEnd,cdsStart,cdsEnd,LastExonStart,LastExonEnd,Sequence,GeneLength,SNPposition
0,chr20,rs3182973,+,57569747,57570139,NELFCD,chr20:57569747-57570139_NELFCD_+,57569938,A,G,57556262,57570188,57556310,57569731,57569696,57570188,gaggcgcgcggccgcgcgtgcgcccgcccgcccgtccccgcctcgc...,13926,13676
1,chr20,rs7397,+,61431004,61431648,MRGBP,chr20:61431004-61431648_MRGBP_+,61431557,A,C,61427804,61431945,61427875,61430995,61430807,61431945,AGTGCGCCTGCGCGGAGCTCGTGGCCGCGCCTGCTCCCGCCGGGGG...,4141,3753
2,chr20,rs8567,+,62522205,62522403,TPD52L2,chr20:62522205-62522403_TPD52L2_+,62522315,A,G,62496642,62522898,62496718,62521298,62521202,62522898,ACGCGGCGAGCTTCTCCCGGCGCCGCCCGCTCGGCTCCCATAGCGC...,26256,25673
3,chr20,rs4810237,+,37434398,37518294,PPP1R16B,chr20:37434398-37518294_PPP1R16B_+,37487150,G,T,37434347,37551667,37464568,37547309,37546799,37551667,CTCTGTCGCCGCTGGAGCAGCTGCGGCTCGGGGACCCACAGACACA...,117320,52803
4,chr20,rs73112067,+,37434398,37518294,PPP1R16B,chr20:37434398-37518294_PPP1R16B_+,37437740,G,A,37434347,37551667,37464568,37547309,37546799,37551667,CTCTGTCGCCGCTGGAGCAGCTGCGGCTCGGGGACCCACAGACACA...,117320,3393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3292,chr18,rs1674719,-,74728178,74844724,MBP,chr18:74728178-74844724_MBP_-,74804251,T,G,74690789,74844774,74692382,74817217,74690789,74692427,ACCATTAAAAGTTTATTGTTTTATTTCAATATTCAGGAACAGTGTA...,153985,40524
3293,chr18,rs899965,-,60795855,60986613,BCL2,chr18:60795855-60986613_BCL2_-,60805011,A,G,60790578,60987361,60795857,60985899,60790578,60795992,CAGTATCTCACACTGTACTTTATTTTTCTTCACAATATTAACTAGA...,196783,182351
3294,chr18,rs2156192,-,60795855,60986613,BCL2,chr18:60795855-60986613_BCL2_-,60917775,G,A,60790578,60987361,60795857,60985899,60790578,60795992,CAGTATCTCACACTGTACTTTATTTTTCTTCACAATATTAACTAGA...,196783,69587
3295,chr18,rs1149357,-,13666435,13671930,FAM210A,chr18:13666435-13671930_FAM210A_-,13667040,T,C,13663349,13726591,13666478,13682076,13663349,13666712,ATTTCAAGGGATAAATTTATTATTTTCACTACTGGGAGGTAGGTAA...,63242,59552
3296,chr18,rs1290354,-,13666435,13671930,FAM210A,chr18:13666435-13671930_FAM210A_-,13668031,C,T,13663349,13726591,13666478,13682076,13663349,13666712,ATTTCAAGGGATAAATTTATTATTTTCACTACTGGGAGGTAGGTAA...,63242,58561

In [40]:
Data.to_csv("Fasta_m6A_QTL_SigSite.csv", index=0)