In [1]:
from Bio import SeqIO
import numpy as np
import pandas as pd

In [2]:
meta=[]
sequence=[]

In [3]:
seq = ('StopCodon.txt')

In [4]:
for seq_record in SeqIO.parse(seq, "fasta"):
    meta.append(str(seq_record.id))
    sequence.append(str(seq_record.seq))

In [5]:
Fasta = pd.DataFrame(data ={'Meta':meta,'Sequence':sequence})

In [6]:
Fasta

,Meta,Sequence
0,chr1:134199224-134235431,TTTTAATTACATTTATTGgtgtgtgagtgtgtgttcacatgcacac...
1,chr1:8361474-9299238,caggtgacatttcacctgcgtgtatgtatatgcaccacgtgtgtat...
2,chr1:25067549-25829707,TGATATGTAGACAAAAGTTTATTTACACCATACAACATTTTAAATA...
3,chr1:33453809-33669795,TAGTCATATACATGTTGTTTATTAGCAAAAACAATCCAAAAGAGGA...
4,chr1:58711559-58758884,GAGCCTCTCAAGCGGCCACTTAGGGCCGGACAGGTACGTGACCTGC...
...,...,...
21626,chr19:60761115-60790693,ACCAATTATGTAAGTATTTTATTTATCACCAAAGAAAAAAACACAG...
21627,chr19:60838747-60861479,TTTCTTTCAAGTATTCAACTCCAGACAGGTTTATTCACAGGGTCAC...
21628,chr19:60864050-60874556,TAAGTCAAAAACGCAAATATTTTAATGTTTATTTTTATTCTATATA...
21629,chr19:61174685-61176309,ccagtattttaaaagattcatccttgtacttctgttactctagaac...
21630,chr19:61224401-61228418,AAATGTTCtggcttttattttacagacatatgattcttctagtact...

In [7]:
Data = pd.read_csv("UniqmRNA_GENCODE_VM7com_mm10_RefSeqpriority_Stop_Codon.csv")

In [8]:
Data

,name,chrom,strand,txStart,txEnd,cdsStart,cdsEnd,StopCodon,Group
0,Adora1,chr1,-,134199224,134235431,134202950,134234355,TAG,2
1,Sntg1,chr1,-,8361474,9299238,8363474,8803943,TGA,2
2,Adgrb3,chr1,-,25067549,25829707,25068167,25826760,TAA,2
3,Prim2,chr1,-,33453809,33669795,33454085,33669011,TAG,2
4,Cflar,chr1,+,58711559,58758884,58726436,58753922,TGA,2
...,...,...,...,...,...,...,...,...,...
21626,Eif3a,chr19,-,60761115,60790693,60762080,60790517,TAA,2
21627,Sfxn4,chr19,-,60838747,60861479,60838972,60861337,TAG,2
21628,Prdx3,chr19,-,60864050,60874556,60864665,60874467,TAG,2
21629,Gm7102,chr19,-,61174685,61176309,61175458,61175995,TAA,1
21630,Csf2ra,chr19,-,61224401,61228418,61225003,61227365,TAG,2

In [9]:
Result = pd.merge(Data, Fasta, left_index=True, right_index=True, how='outer')

In [10]:
Result

,name,chrom,strand,txStart,txEnd,cdsStart,cdsEnd,StopCodon,Group,Meta,Sequence
0,Adora1,chr1,-,134199224,134235431,134202950,134234355,TAG,2,chr1:134199224-134235431,TTTTAATTACATTTATTGgtgtgtgagtgtgtgttcacatgcacac...
1,Sntg1,chr1,-,8361474,9299238,8363474,8803943,TGA,2,chr1:8361474-9299238,caggtgacatttcacctgcgtgtatgtatatgcaccacgtgtgtat...
2,Adgrb3,chr1,-,25067549,25829707,25068167,25826760,TAA,2,chr1:25067549-25829707,TGATATGTAGACAAAAGTTTATTTACACCATACAACATTTTAAATA...
3,Prim2,chr1,-,33453809,33669795,33454085,33669011,TAG,2,chr1:33453809-33669795,TAGTCATATACATGTTGTTTATTAGCAAAAACAATCCAAAAGAGGA...
4,Cflar,chr1,+,58711559,58758884,58726436,58753922,TGA,2,chr1:58711559-58758884,GAGCCTCTCAAGCGGCCACTTAGGGCCGGACAGGTACGTGACCTGC...
...,...,...,...,...,...,...,...,...,...,...,...
21626,Eif3a,chr19,-,60761115,60790693,60762080,60790517,TAA,2,chr19:60761115-60790693,ACCAATTATGTAAGTATTTTATTTATCACCAAAGAAAAAAACACAG...
21627,Sfxn4,chr19,-,60838747,60861479,60838972,60861337,TAG,2,chr19:60838747-60861479,TTTCTTTCAAGTATTCAACTCCAGACAGGTTTATTCACAGGGTCAC...
21628,Prdx3,chr19,-,60864050,60874556,60864665,60874467,TAG,2,chr19:60864050-60874556,TAAGTCAAAAACGCAAATATTTTAATGTTTATTTTTATTCTATATA...
21629,Gm7102,chr19,-,61174685,61176309,61175458,61175995,TAA,1,chr19:61174685-61176309,ccagtattttaaaagattcatccttgtacttctgttactctagaac...
21630,Csf2ra,chr19,-,61224401,61228418,61225003,61227365,TAG,2,chr19:61224401-61228418,AAATGTTCtggcttttattttacagacatatgattcttctagtact...

In [11]:
Result.drop(["Meta"], axis=1, inplace=True)

In [12]:
Result

,name,chrom,strand,txStart,txEnd,cdsStart,cdsEnd,StopCodon,Group,Sequence
0,Adora1,chr1,-,134199224,134235431,134202950,134234355,TAG,2,TTTTAATTACATTTATTGgtgtgtgagtgtgtgttcacatgcacac...
1,Sntg1,chr1,-,8361474,9299238,8363474,8803943,TGA,2,caggtgacatttcacctgcgtgtatgtatatgcaccacgtgtgtat...
2,Adgrb3,chr1,-,25067549,25829707,25068167,25826760,TAA,2,TGATATGTAGACAAAAGTTTATTTACACCATACAACATTTTAAATA...
3,Prim2,chr1,-,33453809,33669795,33454085,33669011,TAG,2,TAGTCATATACATGTTGTTTATTAGCAAAAACAATCCAAAAGAGGA...
4,Cflar,chr1,+,58711559,58758884,58726436,58753922,TGA,2,GAGCCTCTCAAGCGGCCACTTAGGGCCGGACAGGTACGTGACCTGC...
...,...,...,...,...,...,...,...,...,...,...
21626,Eif3a,chr19,-,60761115,60790693,60762080,60790517,TAA,2,ACCAATTATGTAAGTATTTTATTTATCACCAAAGAAAAAAACACAG...
21627,Sfxn4,chr19,-,60838747,60861479,60838972,60861337,TAG,2,TTTCTTTCAAGTATTCAACTCCAGACAGGTTTATTCACAGGGTCAC...
21628,Prdx3,chr19,-,60864050,60874556,60864665,60874467,TAG,2,TAAGTCAAAAACGCAAATATTTTAATGTTTATTTTTATTCTATATA...
21629,Gm7102,chr19,-,61174685,61176309,61175458,61175995,TAA,1,ccagtattttaaaagattcatccttgtacttctgttactctagaac...
21630,Csf2ra,chr19,-,61224401,61228418,61225003,61227365,TAG,2,AAATGTTCtggcttttattttacagacatatgattcttctagtact...

In [13]:
Result["Length"] = Result["txEnd"] - Result["txStart"]

In [14]:
Result

,name,chrom,strand,txStart,txEnd,cdsStart,cdsEnd,StopCodon,Group,Sequence,Length
0,Adora1,chr1,-,134199224,134235431,134202950,134234355,TAG,2,TTTTAATTACATTTATTGgtgtgtgagtgtgtgttcacatgcacac...,36207
1,Sntg1,chr1,-,8361474,9299238,8363474,8803943,TGA,2,caggtgacatttcacctgcgtgtatgtatatgcaccacgtgtgtat...,937764
2,Adgrb3,chr1,-,25067549,25829707,25068167,25826760,TAA,2,TGATATGTAGACAAAAGTTTATTTACACCATACAACATTTTAAATA...,762158
3,Prim2,chr1,-,33453809,33669795,33454085,33669011,TAG,2,TAGTCATATACATGTTGTTTATTAGCAAAAACAATCCAAAAGAGGA...,215986
4,Cflar,chr1,+,58711559,58758884,58726436,58753922,TGA,2,GAGCCTCTCAAGCGGCCACTTAGGGCCGGACAGGTACGTGACCTGC...,47325
...,...,...,...,...,...,...,...,...,...,...,...
21626,Eif3a,chr19,-,60761115,60790693,60762080,60790517,TAA,2,ACCAATTATGTAAGTATTTTATTTATCACCAAAGAAAAAAACACAG...,29578
21627,Sfxn4,chr19,-,60838747,60861479,60838972,60861337,TAG,2,TTTCTTTCAAGTATTCAACTCCAGACAGGTTTATTCACAGGGTCAC...,22732
21628,Prdx3,chr19,-,60864050,60874556,60864665,60874467,TAG,2,TAAGTCAAAAACGCAAATATTTTAATGTTTATTTTTATTCTATATA...,10506
21629,Gm7102,chr19,-,61174685,61176309,61175458,61175995,TAA,1,ccagtattttaaaagattcatccttgtacttctgttactctagaac...,1624
21630,Csf2ra,chr19,-,61224401,61228418,61225003,61227365,TAG,2,AAATGTTCtggcttttattttacagacatatgattcttctagtact...,4017

In [15]:
Result = Result.sort_values(by=["chrom","txStart"], axis=0, ascending=True)
Result = Result.reset_index(drop = True)

In [16]:
Result.to_csv("Fasta_Stop_Codon.csv", index=0)