## Grab sequence

In [1]:
import numpy as np
import pandas as pd

In [2]:
Data = pd.read_csv("/pod/2/ke-lab/LUOZ/m6AAI/UniqmRNA_GENCODE_VM7com_mm10_RefSeqpriority.txt", sep="\t", header=None)

In [3]:
Data.drop([0,11,13,14,15], axis=1, inplace=True)

In [4]:
Data

,1,2,3,4,5,6,7,8,9,10,12
0,ENSMUST00000086465.5,chr1,-,134199224,134235431,134202950,134234355,3,"134199224,134234014,134235227,","134203590,134234412,134235431,",Adora1
1,ENSMUST00000140295.6,chr1,-,8361474,9299238,8363474,8803943,21,"8361474,8414202,8445026,8447979,8463393,846543...","8363633,8414313,8445119,8448132,8463465,846555...",Sntg1
2,ENSMUST00000151309.6,chr1,-,25067549,25829707,25068167,25826760,31,"25067549,25074684,25084243,25093764,25098875,2...","25068356,25074789,25084279,25094408,25098915,2...",Adgrb3
3,ENSMUST00000027312.10,chr1,-,33453809,33669795,33454085,33669011,14,"33453809,33464052,33480457,33484681,33512015,3...","33454304,33464121,33480540,33484808,33512201,3...",Prim2
4,ENSMUST00000114313.6,chr1,+,58711559,58758884,58726436,58753922,10,"58711559,58726305,58729055,58731151,58732252,5...","58711592,58726732,58729161,58731287,58732326,5...",Cflar
...,...,...,...,...,...,...,...,...,...,...,...
22418,ENSMUST00000115964.2,chrX_GL456233_random,+,159646,334183,216736,333326,8,"159646,216735,258246,272713,285395,326113,3324...","159773,216917,258423,272993,285515,326350,3325...",Tmlhe
22419,ENSMUST00000051100.6,chrX_GL456233_random,-,10737,39148,12475,32575,8,"10737,14074,21627,24871,28975,30587,32429,39024,","12544,14167,21695,24962,29113,30645,32584,39148,",Vamp7
22420,ENSMUST00000167421.1,chrX_GL456233_random,+,25189,25788,25189,25788,3,"25189,25540,25762,","25201,25568,25788,",CAAA01165726.1
22421,ENSMUST00000076951.3,chrX_GL456233_random,-,101351,106395,104589,105456,2,"101351,106267,","105572,106395,",Spry3
22422,ENSMUST00000178569.1,chrY_JH584303_random,+,81606,82689,81606,82689,1,"81606,","82689,",AC234645.1

In [5]:
Data[1] = Data[12]

In [6]:
Data.drop([12], axis=1, inplace=True)

In [7]:
Data

,1,2,3,4,5,6,7,8,9,10
0,Adora1,chr1,-,134199224,134235431,134202950,134234355,3,"134199224,134234014,134235227,","134203590,134234412,134235431,"
1,Sntg1,chr1,-,8361474,9299238,8363474,8803943,21,"8361474,8414202,8445026,8447979,8463393,846543...","8363633,8414313,8445119,8448132,8463465,846555..."
2,Adgrb3,chr1,-,25067549,25829707,25068167,25826760,31,"25067549,25074684,25084243,25093764,25098875,2...","25068356,25074789,25084279,25094408,25098915,2..."
3,Prim2,chr1,-,33453809,33669795,33454085,33669011,14,"33453809,33464052,33480457,33484681,33512015,3...","33454304,33464121,33480540,33484808,33512201,3..."
4,Cflar,chr1,+,58711559,58758884,58726436,58753922,10,"58711559,58726305,58729055,58731151,58732252,5...","58711592,58726732,58729161,58731287,58732326,5..."
...,...,...,...,...,...,...,...,...,...,...
22418,Tmlhe,chrX_GL456233_random,+,159646,334183,216736,333326,8,"159646,216735,258246,272713,285395,326113,3324...","159773,216917,258423,272993,285515,326350,3325..."
22419,Vamp7,chrX_GL456233_random,-,10737,39148,12475,32575,8,"10737,14074,21627,24871,28975,30587,32429,39024,","12544,14167,21695,24962,29113,30645,32584,39148,"
22420,CAAA01165726.1,chrX_GL456233_random,+,25189,25788,25189,25788,3,"25189,25540,25762,","25201,25568,25788,"
22421,Spry3,chrX_GL456233_random,-,101351,106395,104589,105456,2,"101351,106267,","105572,106395,"
22422,AC234645.1,chrY_JH584303_random,+,81606,82689,81606,82689,1,"81606,","82689,"

In [8]:
Data.columns = ["name", "chrom", "strand", "txStart", "txEnd", "cdsStart", "cdsEnd", "exonCount", "exonStarts", "exonEnds"]

In [9]:
Data

,name,chrom,strand,txStart,txEnd,cdsStart,cdsEnd,exonCount,exonStarts,exonEnds
0,Adora1,chr1,-,134199224,134235431,134202950,134234355,3,"134199224,134234014,134235227,","134203590,134234412,134235431,"
1,Sntg1,chr1,-,8361474,9299238,8363474,8803943,21,"8361474,8414202,8445026,8447979,8463393,846543...","8363633,8414313,8445119,8448132,8463465,846555..."
2,Adgrb3,chr1,-,25067549,25829707,25068167,25826760,31,"25067549,25074684,25084243,25093764,25098875,2...","25068356,25074789,25084279,25094408,25098915,2..."
3,Prim2,chr1,-,33453809,33669795,33454085,33669011,14,"33453809,33464052,33480457,33484681,33512015,3...","33454304,33464121,33480540,33484808,33512201,3..."
4,Cflar,chr1,+,58711559,58758884,58726436,58753922,10,"58711559,58726305,58729055,58731151,58732252,5...","58711592,58726732,58729161,58731287,58732326,5..."
...,...,...,...,...,...,...,...,...,...,...
22418,Tmlhe,chrX_GL456233_random,+,159646,334183,216736,333326,8,"159646,216735,258246,272713,285395,326113,3324...","159773,216917,258423,272993,285515,326350,3325..."
22419,Vamp7,chrX_GL456233_random,-,10737,39148,12475,32575,8,"10737,14074,21627,24871,28975,30587,32429,39024,","12544,14167,21695,24962,29113,30645,32584,39148,"
22420,CAAA01165726.1,chrX_GL456233_random,+,25189,25788,25189,25788,3,"25189,25540,25762,","25201,25568,25788,"
22421,Spry3,chrX_GL456233_random,-,101351,106395,104589,105456,2,"101351,106267,","105572,106395,"
22422,AC234645.1,chrY_JH584303_random,+,81606,82689,81606,82689,1,"81606,","82689,"

### Select coding genes

In [10]:
idx = (Data["cdsStart"] != Data["cdsEnd"])

In [11]:
Data = Data.loc[idx, ["name", "chrom", "strand", "txStart", "txEnd", "cdsStart", "cdsEnd", "exonCount", "exonStarts", "exonEnds"]]

In [12]:
Data

,name,chrom,strand,txStart,txEnd,cdsStart,cdsEnd,exonCount,exonStarts,exonEnds
0,Adora1,chr1,-,134199224,134235431,134202950,134234355,3,"134199224,134234014,134235227,","134203590,134234412,134235431,"
1,Sntg1,chr1,-,8361474,9299238,8363474,8803943,21,"8361474,8414202,8445026,8447979,8463393,846543...","8363633,8414313,8445119,8448132,8463465,846555..."
2,Adgrb3,chr1,-,25067549,25829707,25068167,25826760,31,"25067549,25074684,25084243,25093764,25098875,2...","25068356,25074789,25084279,25094408,25098915,2..."
3,Prim2,chr1,-,33453809,33669795,33454085,33669011,14,"33453809,33464052,33480457,33484681,33512015,3...","33454304,33464121,33480540,33484808,33512201,3..."
4,Cflar,chr1,+,58711559,58758884,58726436,58753922,10,"58711559,58726305,58729055,58731151,58732252,5...","58711592,58726732,58729161,58731287,58732326,5..."
...,...,...,...,...,...,...,...,...,...,...
22418,Tmlhe,chrX_GL456233_random,+,159646,334183,216736,333326,8,"159646,216735,258246,272713,285395,326113,3324...","159773,216917,258423,272993,285515,326350,3325..."
22419,Vamp7,chrX_GL456233_random,-,10737,39148,12475,32575,8,"10737,14074,21627,24871,28975,30587,32429,39024,","12544,14167,21695,24962,29113,30645,32584,39148,"
22420,CAAA01165726.1,chrX_GL456233_random,+,25189,25788,25189,25788,3,"25189,25540,25762,","25201,25568,25788,"
22421,Spry3,chrX_GL456233_random,-,101351,106395,104589,105456,2,"101351,106267,","105572,106395,"
22422,AC234645.1,chrY_JH584303_random,+,81606,82689,81606,82689,1,"81606,","82689,"

### Keep standard chromosomes

In [13]:
Data = Data[:22357]

### exonCount > 1

In [14]:
Data = Data[Data.exonCount > 1]

In [15]:
Data = Data.reset_index(drop = True)

In [16]:
Data

,name,chrom,strand,txStart,txEnd,cdsStart,cdsEnd,exonCount,exonStarts,exonEnds
0,Adora1,chr1,-,134199224,134235431,134202950,134234355,3,"134199224,134234014,134235227,","134203590,134234412,134235431,"
1,Sntg1,chr1,-,8361474,9299238,8363474,8803943,21,"8361474,8414202,8445026,8447979,8463393,846543...","8363633,8414313,8445119,8448132,8463465,846555..."
2,Adgrb3,chr1,-,25067549,25829707,25068167,25826760,31,"25067549,25074684,25084243,25093764,25098875,2...","25068356,25074789,25084279,25094408,25098915,2..."
3,Prim2,chr1,-,33453809,33669795,33454085,33669011,14,"33453809,33464052,33480457,33484681,33512015,3...","33454304,33464121,33480540,33484808,33512201,3..."
4,Cflar,chr1,+,58711559,58758884,58726436,58753922,10,"58711559,58726305,58729055,58731151,58732252,5...","58711592,58726732,58729161,58731287,58732326,5..."
...,...,...,...,...,...,...,...,...,...,...
19628,Fam204a,chr19,-,60198585,60226697,60199435,60221296,8,"60198585,60199969,60212672,60220039,60220329,6...","60199487,60200076,60212762,60220139,60220360,6..."
19629,Eif3a,chr19,-,60761115,60790693,60762080,60790517,22,"60761115,60763064,60764031,60766333,60767574,6...","60762304,60763264,60764233,60766995,60767663,6..."
19630,Sfxn4,chr19,-,60838747,60861479,60838972,60861337,14,"60838747,60842118,60844208,60850958,60852011,6...","60839050,60842236,60844294,60851074,60852090,6..."
19631,Prdx3,chr19,-,60864050,60874556,60864665,60874467,7,"60864050,60865165,60867515,60870003,60871419,6...","60864719,60865331,60867619,60870139,60871561,6..."
19632,Csf2ra,chr19,-,61224401,61228418,61225003,61227365,12,"61224401,61225132,61225323,61225522,61225791,6...","61225033,61225214,61225420,61225652,61225821,6..."

In [17]:
Data["LastExonStart"] = 0
Data["LastExonEnd"] = 0

In [18]:
Data

,name,chrom,strand,txStart,txEnd,cdsStart,cdsEnd,exonCount,exonStarts,exonEnds,LastExonStart,LastExonEnd
0,Adora1,chr1,-,134199224,134235431,134202950,134234355,3,"134199224,134234014,134235227,","134203590,134234412,134235431,",0,0
1,Sntg1,chr1,-,8361474,9299238,8363474,8803943,21,"8361474,8414202,8445026,8447979,8463393,846543...","8363633,8414313,8445119,8448132,8463465,846555...",0,0
2,Adgrb3,chr1,-,25067549,25829707,25068167,25826760,31,"25067549,25074684,25084243,25093764,25098875,2...","25068356,25074789,25084279,25094408,25098915,2...",0,0
3,Prim2,chr1,-,33453809,33669795,33454085,33669011,14,"33453809,33464052,33480457,33484681,33512015,3...","33454304,33464121,33480540,33484808,33512201,3...",0,0
4,Cflar,chr1,+,58711559,58758884,58726436,58753922,10,"58711559,58726305,58729055,58731151,58732252,5...","58711592,58726732,58729161,58731287,58732326,5...",0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
19628,Fam204a,chr19,-,60198585,60226697,60199435,60221296,8,"60198585,60199969,60212672,60220039,60220329,6...","60199487,60200076,60212762,60220139,60220360,6...",0,0
19629,Eif3a,chr19,-,60761115,60790693,60762080,60790517,22,"60761115,60763064,60764031,60766333,60767574,6...","60762304,60763264,60764233,60766995,60767663,6...",0,0
19630,Sfxn4,chr19,-,60838747,60861479,60838972,60861337,14,"60838747,60842118,60844208,60850958,60852011,6...","60839050,60842236,60844294,60851074,60852090,6...",0,0
19631,Prdx3,chr19,-,60864050,60874556,60864665,60874467,7,"60864050,60865165,60867515,60870003,60871419,6...","60864719,60865331,60867619,60870139,60871561,6...",0,0
19632,Csf2ra,chr19,-,61224401,61228418,61225003,61227365,12,"61224401,61225132,61225323,61225522,61225791,6...","61225033,61225214,61225420,61225652,61225821,6...",0,0

In [19]:
for i in range(len(Data)):
    if Data.loc[i, "strand"] == "+":
        Data.loc[i,("LastExonStart")] = Data.loc[i, "exonStarts"].split(",")[-2]
        Data.loc[i,("LastExonEnd")] = Data.loc[i, "exonEnds"].split(",")[-2]
    elif Data.loc[i, "strand"] == "-":
        Data.loc[i,("LastExonStart")] = Data.loc[i, "exonStarts"].split(",")[0]
        Data.loc[i,("LastExonEnd")] = Data.loc[i, "exonEnds"].split(",")[0]

In [20]:
Data

,name,chrom,strand,txStart,txEnd,cdsStart,cdsEnd,exonCount,exonStarts,exonEnds,LastExonStart,LastExonEnd
0,Adora1,chr1,-,134199224,134235431,134202950,134234355,3,"134199224,134234014,134235227,","134203590,134234412,134235431,",134199224,134203590
1,Sntg1,chr1,-,8361474,9299238,8363474,8803943,21,"8361474,8414202,8445026,8447979,8463393,846543...","8363633,8414313,8445119,8448132,8463465,846555...",8361474,8363633
2,Adgrb3,chr1,-,25067549,25829707,25068167,25826760,31,"25067549,25074684,25084243,25093764,25098875,2...","25068356,25074789,25084279,25094408,25098915,2...",25067549,25068356
3,Prim2,chr1,-,33453809,33669795,33454085,33669011,14,"33453809,33464052,33480457,33484681,33512015,3...","33454304,33464121,33480540,33484808,33512201,3...",33453809,33454304
4,Cflar,chr1,+,58711559,58758884,58726436,58753922,10,"58711559,58726305,58729055,58731151,58732252,5...","58711592,58726732,58729161,58731287,58732326,5...",58753783,58758884
...,...,...,...,...,...,...,...,...,...,...,...,...
19628,Fam204a,chr19,-,60198585,60226697,60199435,60221296,8,"60198585,60199969,60212672,60220039,60220329,6...","60199487,60200076,60212762,60220139,60220360,6...",60198585,60199487
19629,Eif3a,chr19,-,60761115,60790693,60762080,60790517,22,"60761115,60763064,60764031,60766333,60767574,6...","60762304,60763264,60764233,60766995,60767663,6...",60761115,60762304
19630,Sfxn4,chr19,-,60838747,60861479,60838972,60861337,14,"60838747,60842118,60844208,60850958,60852011,6...","60839050,60842236,60844294,60851074,60852090,6...",60838747,60839050
19631,Prdx3,chr19,-,60864050,60874556,60864665,60874467,7,"60864050,60865165,60867515,60870003,60871419,6...","60864719,60865331,60867619,60870139,60871561,6...",60864050,60864719
19632,Csf2ra,chr19,-,61224401,61228418,61225003,61227365,12,"61224401,61225132,61225323,61225522,61225791,6...","61225033,61225214,61225420,61225652,61225821,6...",61224401,61225033

In [21]:
Data.drop(["exonCount", "exonStarts", "exonEnds"], axis=1, inplace=True)

In [22]:
Data

,name,chrom,strand,txStart,txEnd,cdsStart,cdsEnd,LastExonStart,LastExonEnd
0,Adora1,chr1,-,134199224,134235431,134202950,134234355,134199224,134203590
1,Sntg1,chr1,-,8361474,9299238,8363474,8803943,8361474,8363633
2,Adgrb3,chr1,-,25067549,25829707,25068167,25826760,25067549,25068356
3,Prim2,chr1,-,33453809,33669795,33454085,33669011,33453809,33454304
4,Cflar,chr1,+,58711559,58758884,58726436,58753922,58753783,58758884
...,...,...,...,...,...,...,...,...,...
19628,Fam204a,chr19,-,60198585,60226697,60199435,60221296,60198585,60199487
19629,Eif3a,chr19,-,60761115,60790693,60762080,60790517,60761115,60762304
19630,Sfxn4,chr19,-,60838747,60861479,60838972,60861337,60838747,60839050
19631,Prdx3,chr19,-,60864050,60874556,60864665,60874467,60864050,60864719
19632,Csf2ra,chr19,-,61224401,61228418,61225003,61227365,61224401,61225033

### m6A sites

In [23]:
Site = pd.read_csv("M6A_CodonSwap.csv")

In [24]:
Site

      chrom     name strand      Start        End  Probabilty
0     chr19     Add3      +   53245404   53245405    0.950052
1      chr5    Stim2      +   54119062   54119063    0.947187
2      chr9   Atp2c1      -  105412963  105412964    0.944073
3      chr9   Dopey1      +   86554292   86554293    0.941125
4      chr4   Zfp462      +   55080998   55080999    0.939202
...     ...      ...    ...        ...        ...         ...
7397   chr2    Casc5      +  119104024  119104025    0.000179
7398   chr4    Capzb      +  139291784  139291785    0.000121
7399   chr7  Pgpep1l      -   68236646   68236647    0.000102
7400  chr19    Kcnk4      -    6925717    6925718    0.000033
7401  chr14     Zic2      +  122479847  122479848    0.000001

[7402 rows x 6 columns]

In [25]:
Site.rename(columns={"Start":"m6AStart","End":"m6AEnd"}, inplace = True)

In [26]:
Overlap = pd.merge(Data, Site, how="inner", on=["chrom", "name", "strand"])

In [27]:
Overlap

,name,chrom,strand,txStart,txEnd,cdsStart,cdsEnd,LastExonStart,LastExonEnd,m6AStart,m6AEnd,Probabilty
0,Adora1,chr1,-,134199224,134235431,134202950,134234355,134199224,134203590,134202134,134202135,0.351499
1,Sntg1,chr1,-,8361474,9299238,8363474,8803943,8361474,8363633,8363412,8363413,0.369057
2,Adgrb3,chr1,-,25067549,25829707,25068167,25826760,25067549,25068356,25068152,25068153,0.703083
3,Prim2,chr1,-,33453809,33669795,33454085,33669011,33453809,33454304,33454113,33454114,0.466319
4,Gpr39,chr1,+,125676994,125873862,125677336,125872884,125872369,125873862,125872731,125872732,0.559050
...,...,...,...,...,...,...,...,...,...,...,...,...
7397,Pdzd8,chr19,-,59296083,59345780,59299522,59345587,59296083,59301708,59299580,59299581,0.722710
7398,Emx2,chr19,+,59458371,59465357,59459215,59464047,59463879,59465357,59464075,59464076,0.637705
7399,Rab11fip2,chr19,-,59902883,59943654,59906915,59937357,59902883,59907143,59906900,59906901,0.683555
7400,Eif3a,chr19,-,60761115,60790693,60762080,60790517,60761115,60762304,60762115,60762116,0.314171
7401,Csf2ra,chr19,-,61224401,61228418,61225003,61227365,61224401,61225033,61224988,61224989,0.778313

In [28]:
Overlap["LastExonStart"] = Overlap["LastExonStart"].astype(int)
Overlap["LastExonEnd"] = Overlap["LastExonEnd"].astype(int)

In [29]:
Positive = Overlap[Overlap["strand"]=="+"]
Positive = Positive.reset_index(drop = True)

In [30]:
Negative = Overlap[Overlap["strand"]=="-"]
Negative = Negative.reset_index(drop = True)

### Select m6A sites in the Coding region of LastExon

In [31]:
Positive = Positive[(Positive["m6AStart"] < Positive["cdsEnd"])&(Positive["m6AStart"] > Positive["LastExonStart"])]

In [32]:
Positive

,name,chrom,strand,txStart,txEnd,cdsStart,cdsEnd,LastExonStart,LastExonEnd,m6AStart,m6AEnd,Probabilty
0,Gpr39,chr1,+,125676994,125873862,125677336,125872884,125872369,125873862,125872731,125872732,0.559050
2,Plcl1,chr1,+,55405920,55754285,55406387,55751463,55751280,55754285,55751363,55751364,0.465679
6,Cdh20,chr1,+,104768528,104995481,104934096,104994385,104993879,104995481,104994314,104994315,0.752332
7,Cdh7,chr1,+,109983736,110139001,109994179,110138355,110137861,110139001,110138138,110138139,0.811570
8,Cntnap5a,chr1,+,115684755,116587323,115685136,116580674,116580480,116587323,116580597,116580598,0.135139
...,...,...,...,...,...,...,...,...,...,...,...,...
3674,Trim8,chr19,+,46501647,46516444,46502443,46515666,46515058,46516444,46515657,46515658,0.703754
3678,Ina,chr19,+,47014697,47025327,47014754,47023650,47023334,47025327,47023566,47023567,0.392881
3679,Taf5,chr19,+,47067747,47083479,47067764,47082644,47082426,47083479,47082485,47082486,0.723194
3680,Pdcd11,chr19,+,47090765,47131143,47092798,47130810,47130638,47131143,47130712,47130713,0.352127
3685,Trub1,chr19,+,57452905,57491005,57452946,57488268,57488008,57491005,57488194,57488195,0.600773

In [33]:
Negative = Negative[(Negative["m6AStart"] > Negative["cdsStart"])&(Negative["m6AStart"] < Negative["LastExonEnd"])]

In [34]:
Negative

,name,chrom,strand,txStart,txEnd,cdsStart,cdsEnd,LastExonStart,LastExonEnd,m6AStart,m6AEnd,Probabilty
3,Prim2,chr1,-,33453809,33669795,33454085,33669011,33453809,33454304,33454113,33454114,0.466319
4,Pld5,chr1,-,175962305,176275298,175963827,176274874,175962305,175964084,175963975,175963976,0.539744
5,Syt14,chr1,-,192891232,193035775,192897306,193035635,192891232,192897620,192897481,192897482,0.276559
14,Camsap2,chr1,-,136268122,136346104,136270841,136345437,136268122,136271147,136270991,136270992,0.894186
23,Rgs20,chr1,-,4909575,5070285,4910473,5070177,4909575,4910662,4910552,4910553,0.354980
...,...,...,...,...,...,...,...,...,...,...,...,...
3700,Lbx1,chr19,-,45232683,45235812,45233733,45235227,45232683,45234257,45234013,45234014,0.526412
3701,Poll,chr19,-,45552274,45560531,45552805,45559691,45552274,45553170,45552812,45552813,0.853962
3708,Ccdc186,chr19,-,56790962,56813683,56790962,56813683,56790962,56791046,56791013,56791014,0.001048
3710,Pdzd8,chr19,-,59296083,59345780,59299522,59345587,59296083,59301708,59299580,59299581,0.722710
3712,Eif3a,chr19,-,60761115,60790693,60762080,60790517,60761115,60762304,60762115,60762116,0.314171

In [35]:
Data = Positive.append(Negative)
Data = Data.reset_index(drop = True)

In [36]:
Data

,name,chrom,strand,txStart,txEnd,cdsStart,cdsEnd,LastExonStart,LastExonEnd,m6AStart,m6AEnd,Probabilty
0,Gpr39,chr1,+,125676994,125873862,125677336,125872884,125872369,125873862,125872731,125872732,0.559050
1,Plcl1,chr1,+,55405920,55754285,55406387,55751463,55751280,55754285,55751363,55751364,0.465679
2,Cdh20,chr1,+,104768528,104995481,104934096,104994385,104993879,104995481,104994314,104994315,0.752332
3,Cdh7,chr1,+,109983736,110139001,109994179,110138355,110137861,110139001,110138138,110138139,0.811570
4,Cntnap5a,chr1,+,115684755,116587323,115685136,116580674,116580480,116587323,116580597,116580598,0.135139
...,...,...,...,...,...,...,...,...,...,...,...,...
2479,Lbx1,chr19,-,45232683,45235812,45233733,45235227,45232683,45234257,45234013,45234014,0.526412
2480,Poll,chr19,-,45552274,45560531,45552805,45559691,45552274,45553170,45552812,45552813,0.853962
2481,Ccdc186,chr19,-,56790962,56813683,56790962,56813683,56790962,56791046,56791013,56791014,0.001048
2482,Pdzd8,chr19,-,59296083,59345780,59299522,59345587,59296083,59301708,59299580,59299581,0.722710
2483,Eif3a,chr19,-,60761115,60790693,60762080,60790517,60761115,60762304,60762115,60762116,0.314171

In [37]:
Data.to_csv("CodonSwap.csv", index=0)

### Create Bed

In [38]:
Bed = Data.iloc[:, [1, 3, 4]]

In [39]:
Bed.to_csv("CodonSwap.bed", sep="\t", header=False, index=False)

In [40]:
!bedtools getfasta -bed CodonSwap.bed -fi /pod/2/ke-lab/LUOZ/Reference/Fasta/mm10/mm10.fa -fo CodonSwap.txt