## Grab sequence

In [1]:
import numpy as np
import pandas as pd

In [2]:
Data = pd.read_csv("/pod/2/ke-lab/LUOZ/m6AAI/UniqmRNA_GENCODE_VM7com_mm10_RefSeqpriority.txt", sep="\t", header=None)

In [3]:
Data.drop([0,11,13,14,15], axis=1, inplace=True)

In [4]:
Data

,1,2,3,4,5,6,7,8,9,10,12
0,ENSMUST00000086465.5,chr1,-,134199224,134235431,134202950,134234355,3,"134199224,134234014,134235227,","134203590,134234412,134235431,",Adora1
1,ENSMUST00000140295.6,chr1,-,8361474,9299238,8363474,8803943,21,"8361474,8414202,8445026,8447979,8463393,846543...","8363633,8414313,8445119,8448132,8463465,846555...",Sntg1
2,ENSMUST00000151309.6,chr1,-,25067549,25829707,25068167,25826760,31,"25067549,25074684,25084243,25093764,25098875,2...","25068356,25074789,25084279,25094408,25098915,2...",Adgrb3
3,ENSMUST00000027312.10,chr1,-,33453809,33669795,33454085,33669011,14,"33453809,33464052,33480457,33484681,33512015,3...","33454304,33464121,33480540,33484808,33512201,3...",Prim2
4,ENSMUST00000114313.6,chr1,+,58711559,58758884,58726436,58753922,10,"58711559,58726305,58729055,58731151,58732252,5...","58711592,58726732,58729161,58731287,58732326,5...",Cflar
...,...,...,...,...,...,...,...,...,...,...,...
22418,ENSMUST00000115964.2,chrX_GL456233_random,+,159646,334183,216736,333326,8,"159646,216735,258246,272713,285395,326113,3324...","159773,216917,258423,272993,285515,326350,3325...",Tmlhe
22419,ENSMUST00000051100.6,chrX_GL456233_random,-,10737,39148,12475,32575,8,"10737,14074,21627,24871,28975,30587,32429,39024,","12544,14167,21695,24962,29113,30645,32584,39148,",Vamp7
22420,ENSMUST00000167421.1,chrX_GL456233_random,+,25189,25788,25189,25788,3,"25189,25540,25762,","25201,25568,25788,",CAAA01165726.1
22421,ENSMUST00000076951.3,chrX_GL456233_random,-,101351,106395,104589,105456,2,"101351,106267,","105572,106395,",Spry3
22422,ENSMUST00000178569.1,chrY_JH584303_random,+,81606,82689,81606,82689,1,"81606,","82689,",AC234645.1

In [5]:
Data[1] = Data[12]

In [6]:
Data.drop([12], axis=1, inplace=True)

In [7]:
Data

,1,2,3,4,5,6,7,8,9,10
0,Adora1,chr1,-,134199224,134235431,134202950,134234355,3,"134199224,134234014,134235227,","134203590,134234412,134235431,"
1,Sntg1,chr1,-,8361474,9299238,8363474,8803943,21,"8361474,8414202,8445026,8447979,8463393,846543...","8363633,8414313,8445119,8448132,8463465,846555..."
2,Adgrb3,chr1,-,25067549,25829707,25068167,25826760,31,"25067549,25074684,25084243,25093764,25098875,2...","25068356,25074789,25084279,25094408,25098915,2..."
3,Prim2,chr1,-,33453809,33669795,33454085,33669011,14,"33453809,33464052,33480457,33484681,33512015,3...","33454304,33464121,33480540,33484808,33512201,3..."
4,Cflar,chr1,+,58711559,58758884,58726436,58753922,10,"58711559,58726305,58729055,58731151,58732252,5...","58711592,58726732,58729161,58731287,58732326,5..."
...,...,...,...,...,...,...,...,...,...,...
22418,Tmlhe,chrX_GL456233_random,+,159646,334183,216736,333326,8,"159646,216735,258246,272713,285395,326113,3324...","159773,216917,258423,272993,285515,326350,3325..."
22419,Vamp7,chrX_GL456233_random,-,10737,39148,12475,32575,8,"10737,14074,21627,24871,28975,30587,32429,39024,","12544,14167,21695,24962,29113,30645,32584,39148,"
22420,CAAA01165726.1,chrX_GL456233_random,+,25189,25788,25189,25788,3,"25189,25540,25762,","25201,25568,25788,"
22421,Spry3,chrX_GL456233_random,-,101351,106395,104589,105456,2,"101351,106267,","105572,106395,"
22422,AC234645.1,chrY_JH584303_random,+,81606,82689,81606,82689,1,"81606,","82689,"

In [8]:
Data.columns = ["name", "chrom", "strand", "txStart", "txEnd", "cdsStart", "cdsEnd", "exonCount", "exonStarts", "exonEnds"]

In [9]:
Data

,name,chrom,strand,txStart,txEnd,cdsStart,cdsEnd,exonCount,exonStarts,exonEnds
0,Adora1,chr1,-,134199224,134235431,134202950,134234355,3,"134199224,134234014,134235227,","134203590,134234412,134235431,"
1,Sntg1,chr1,-,8361474,9299238,8363474,8803943,21,"8361474,8414202,8445026,8447979,8463393,846543...","8363633,8414313,8445119,8448132,8463465,846555..."
2,Adgrb3,chr1,-,25067549,25829707,25068167,25826760,31,"25067549,25074684,25084243,25093764,25098875,2...","25068356,25074789,25084279,25094408,25098915,2..."
3,Prim2,chr1,-,33453809,33669795,33454085,33669011,14,"33453809,33464052,33480457,33484681,33512015,3...","33454304,33464121,33480540,33484808,33512201,3..."
4,Cflar,chr1,+,58711559,58758884,58726436,58753922,10,"58711559,58726305,58729055,58731151,58732252,5...","58711592,58726732,58729161,58731287,58732326,5..."
...,...,...,...,...,...,...,...,...,...,...
22418,Tmlhe,chrX_GL456233_random,+,159646,334183,216736,333326,8,"159646,216735,258246,272713,285395,326113,3324...","159773,216917,258423,272993,285515,326350,3325..."
22419,Vamp7,chrX_GL456233_random,-,10737,39148,12475,32575,8,"10737,14074,21627,24871,28975,30587,32429,39024,","12544,14167,21695,24962,29113,30645,32584,39148,"
22420,CAAA01165726.1,chrX_GL456233_random,+,25189,25788,25189,25788,3,"25189,25540,25762,","25201,25568,25788,"
22421,Spry3,chrX_GL456233_random,-,101351,106395,104589,105456,2,"101351,106267,","105572,106395,"
22422,AC234645.1,chrY_JH584303_random,+,81606,82689,81606,82689,1,"81606,","82689,"

### Select coding genes

In [10]:
idx = (Data["cdsStart"] != Data["cdsEnd"])

In [11]:
Data = Data.loc[idx, ["name", "chrom", "strand", "txStart", "txEnd", "cdsStart", "cdsEnd", "exonCount", "exonStarts", "exonEnds"]]

In [12]:
Data

,name,chrom,strand,txStart,txEnd,cdsStart,cdsEnd,exonCount,exonStarts,exonEnds
0,Adora1,chr1,-,134199224,134235431,134202950,134234355,3,"134199224,134234014,134235227,","134203590,134234412,134235431,"
1,Sntg1,chr1,-,8361474,9299238,8363474,8803943,21,"8361474,8414202,8445026,8447979,8463393,846543...","8363633,8414313,8445119,8448132,8463465,846555..."
2,Adgrb3,chr1,-,25067549,25829707,25068167,25826760,31,"25067549,25074684,25084243,25093764,25098875,2...","25068356,25074789,25084279,25094408,25098915,2..."
3,Prim2,chr1,-,33453809,33669795,33454085,33669011,14,"33453809,33464052,33480457,33484681,33512015,3...","33454304,33464121,33480540,33484808,33512201,3..."
4,Cflar,chr1,+,58711559,58758884,58726436,58753922,10,"58711559,58726305,58729055,58731151,58732252,5...","58711592,58726732,58729161,58731287,58732326,5..."
...,...,...,...,...,...,...,...,...,...,...
22418,Tmlhe,chrX_GL456233_random,+,159646,334183,216736,333326,8,"159646,216735,258246,272713,285395,326113,3324...","159773,216917,258423,272993,285515,326350,3325..."
22419,Vamp7,chrX_GL456233_random,-,10737,39148,12475,32575,8,"10737,14074,21627,24871,28975,30587,32429,39024,","12544,14167,21695,24962,29113,30645,32584,39148,"
22420,CAAA01165726.1,chrX_GL456233_random,+,25189,25788,25189,25788,3,"25189,25540,25762,","25201,25568,25788,"
22421,Spry3,chrX_GL456233_random,-,101351,106395,104589,105456,2,"101351,106267,","105572,106395,"
22422,AC234645.1,chrY_JH584303_random,+,81606,82689,81606,82689,1,"81606,","82689,"

### Keep standard chromosomes

In [13]:
Data = Data[:22357]

### exonCount > 1

In [14]:
Data = Data[Data.exonCount > 1]

In [15]:
Data = Data.reset_index(drop = True)

In [16]:
Data

,name,chrom,strand,txStart,txEnd,cdsStart,cdsEnd,exonCount,exonStarts,exonEnds
0,Adora1,chr1,-,134199224,134235431,134202950,134234355,3,"134199224,134234014,134235227,","134203590,134234412,134235431,"
1,Sntg1,chr1,-,8361474,9299238,8363474,8803943,21,"8361474,8414202,8445026,8447979,8463393,846543...","8363633,8414313,8445119,8448132,8463465,846555..."
2,Adgrb3,chr1,-,25067549,25829707,25068167,25826760,31,"25067549,25074684,25084243,25093764,25098875,2...","25068356,25074789,25084279,25094408,25098915,2..."
3,Prim2,chr1,-,33453809,33669795,33454085,33669011,14,"33453809,33464052,33480457,33484681,33512015,3...","33454304,33464121,33480540,33484808,33512201,3..."
4,Cflar,chr1,+,58711559,58758884,58726436,58753922,10,"58711559,58726305,58729055,58731151,58732252,5...","58711592,58726732,58729161,58731287,58732326,5..."
...,...,...,...,...,...,...,...,...,...,...
19628,Fam204a,chr19,-,60198585,60226697,60199435,60221296,8,"60198585,60199969,60212672,60220039,60220329,6...","60199487,60200076,60212762,60220139,60220360,6..."
19629,Eif3a,chr19,-,60761115,60790693,60762080,60790517,22,"60761115,60763064,60764031,60766333,60767574,6...","60762304,60763264,60764233,60766995,60767663,6..."
19630,Sfxn4,chr19,-,60838747,60861479,60838972,60861337,14,"60838747,60842118,60844208,60850958,60852011,6...","60839050,60842236,60844294,60851074,60852090,6..."
19631,Prdx3,chr19,-,60864050,60874556,60864665,60874467,7,"60864050,60865165,60867515,60870003,60871419,6...","60864719,60865331,60867619,60870139,60871561,6..."
19632,Csf2ra,chr19,-,61224401,61228418,61225003,61227365,12,"61224401,61225132,61225323,61225522,61225791,6...","61225033,61225214,61225420,61225652,61225821,6..."

In [17]:
Data["LastExonStart"] = 0
Data["LastExonEnd"] = 0

In [18]:
Data

,name,chrom,strand,txStart,txEnd,cdsStart,cdsEnd,exonCount,exonStarts,exonEnds,LastExonStart,LastExonEnd
0,Adora1,chr1,-,134199224,134235431,134202950,134234355,3,"134199224,134234014,134235227,","134203590,134234412,134235431,",0,0
1,Sntg1,chr1,-,8361474,9299238,8363474,8803943,21,"8361474,8414202,8445026,8447979,8463393,846543...","8363633,8414313,8445119,8448132,8463465,846555...",0,0
2,Adgrb3,chr1,-,25067549,25829707,25068167,25826760,31,"25067549,25074684,25084243,25093764,25098875,2...","25068356,25074789,25084279,25094408,25098915,2...",0,0
3,Prim2,chr1,-,33453809,33669795,33454085,33669011,14,"33453809,33464052,33480457,33484681,33512015,3...","33454304,33464121,33480540,33484808,33512201,3...",0,0
4,Cflar,chr1,+,58711559,58758884,58726436,58753922,10,"58711559,58726305,58729055,58731151,58732252,5...","58711592,58726732,58729161,58731287,58732326,5...",0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
19628,Fam204a,chr19,-,60198585,60226697,60199435,60221296,8,"60198585,60199969,60212672,60220039,60220329,6...","60199487,60200076,60212762,60220139,60220360,6...",0,0
19629,Eif3a,chr19,-,60761115,60790693,60762080,60790517,22,"60761115,60763064,60764031,60766333,60767574,6...","60762304,60763264,60764233,60766995,60767663,6...",0,0
19630,Sfxn4,chr19,-,60838747,60861479,60838972,60861337,14,"60838747,60842118,60844208,60850958,60852011,6...","60839050,60842236,60844294,60851074,60852090,6...",0,0
19631,Prdx3,chr19,-,60864050,60874556,60864665,60874467,7,"60864050,60865165,60867515,60870003,60871419,6...","60864719,60865331,60867619,60870139,60871561,6...",0,0
19632,Csf2ra,chr19,-,61224401,61228418,61225003,61227365,12,"61224401,61225132,61225323,61225522,61225791,6...","61225033,61225214,61225420,61225652,61225821,6...",0,0

In [19]:
for i in range(len(Data)):
    if Data.loc[i, "strand"] == "+":
        Data.loc[i,("LastExonStart")] = Data.loc[i, "exonStarts"].split(",")[-2]
        Data.loc[i,("LastExonEnd")] = Data.loc[i, "exonEnds"].split(",")[-2]
    elif Data.loc[i, "strand"] == "-":
        Data.loc[i,("LastExonStart")] = Data.loc[i, "exonStarts"].split(",")[0]
        Data.loc[i,("LastExonEnd")] = Data.loc[i, "exonEnds"].split(",")[0]

In [20]:
Data

,name,chrom,strand,txStart,txEnd,cdsStart,cdsEnd,exonCount,exonStarts,exonEnds,LastExonStart,LastExonEnd
0,Adora1,chr1,-,134199224,134235431,134202950,134234355,3,"134199224,134234014,134235227,","134203590,134234412,134235431,",134199224,134203590
1,Sntg1,chr1,-,8361474,9299238,8363474,8803943,21,"8361474,8414202,8445026,8447979,8463393,846543...","8363633,8414313,8445119,8448132,8463465,846555...",8361474,8363633
2,Adgrb3,chr1,-,25067549,25829707,25068167,25826760,31,"25067549,25074684,25084243,25093764,25098875,2...","25068356,25074789,25084279,25094408,25098915,2...",25067549,25068356
3,Prim2,chr1,-,33453809,33669795,33454085,33669011,14,"33453809,33464052,33480457,33484681,33512015,3...","33454304,33464121,33480540,33484808,33512201,3...",33453809,33454304
4,Cflar,chr1,+,58711559,58758884,58726436,58753922,10,"58711559,58726305,58729055,58731151,58732252,5...","58711592,58726732,58729161,58731287,58732326,5...",58753783,58758884
...,...,...,...,...,...,...,...,...,...,...,...,...
19628,Fam204a,chr19,-,60198585,60226697,60199435,60221296,8,"60198585,60199969,60212672,60220039,60220329,6...","60199487,60200076,60212762,60220139,60220360,6...",60198585,60199487
19629,Eif3a,chr19,-,60761115,60790693,60762080,60790517,22,"60761115,60763064,60764031,60766333,60767574,6...","60762304,60763264,60764233,60766995,60767663,6...",60761115,60762304
19630,Sfxn4,chr19,-,60838747,60861479,60838972,60861337,14,"60838747,60842118,60844208,60850958,60852011,6...","60839050,60842236,60844294,60851074,60852090,6...",60838747,60839050
19631,Prdx3,chr19,-,60864050,60874556,60864665,60874467,7,"60864050,60865165,60867515,60870003,60871419,6...","60864719,60865331,60867619,60870139,60871561,6...",60864050,60864719
19632,Csf2ra,chr19,-,61224401,61228418,61225003,61227365,12,"61224401,61225132,61225323,61225522,61225791,6...","61225033,61225214,61225420,61225652,61225821,6...",61224401,61225033

In [21]:
Data.drop(["exonCount", "exonStarts", "exonEnds"], axis=1, inplace=True)

In [22]:
Data

,name,chrom,strand,txStart,txEnd,cdsStart,cdsEnd,LastExonStart,LastExonEnd
0,Adora1,chr1,-,134199224,134235431,134202950,134234355,134199224,134203590
1,Sntg1,chr1,-,8361474,9299238,8363474,8803943,8361474,8363633
2,Adgrb3,chr1,-,25067549,25829707,25068167,25826760,25067549,25068356
3,Prim2,chr1,-,33453809,33669795,33454085,33669011,33453809,33454304
4,Cflar,chr1,+,58711559,58758884,58726436,58753922,58753783,58758884
...,...,...,...,...,...,...,...,...,...
19628,Fam204a,chr19,-,60198585,60226697,60199435,60221296,60198585,60199487
19629,Eif3a,chr19,-,60761115,60790693,60762080,60790517,60761115,60762304
19630,Sfxn4,chr19,-,60838747,60861479,60838972,60861337,60838747,60839050
19631,Prdx3,chr19,-,60864050,60874556,60864665,60874467,60864050,60864719
19632,Csf2ra,chr19,-,61224401,61228418,61225003,61227365,61224401,61225033

### m6A sites

In [23]:
Site = pd.read_csv("mm10_Low_M6ASites.csv")

In [24]:
Site

       chrom     name strand      Start        End    Probabilty
0      chr15     Adsl      +   80970364   80970365  9.999087e-03
1       chr7  Olfr710      -  106944844  106944845  9.996847e-03
2      chr14   Gm3327      +   44128799   44128800  9.996416e-03
3      chr11    Dbil5      +   76218386   76218387  9.996005e-03
4      chr14    Atxn7      +   14106595   14106596  9.995905e-03
...      ...      ...    ...        ...        ...           ...
96004   chr9   Gm5916      -   36119960   36119961  1.010176e-07
96005   chr4     Ago3      -  126339010  126339011  1.008939e-07
96006   chr3  Dnajb14      +  137911305  137911306  1.005635e-07
96007  chr15  Arfgap3      -   83299752   83299753  1.004757e-07
96008   chr3     Tnik      +   28670467   28670468  1.003057e-07

[96009 rows x 6 columns]

In [25]:
Site.rename(columns={"Start":"m6AStart","End":"m6AEnd"}, inplace = True)

In [26]:
Overlap = pd.merge(Data, Site, how="inner", on=["chrom", "name", "strand"])

In [27]:
Overlap

,name,chrom,strand,txStart,txEnd,cdsStart,cdsEnd,LastExonStart,LastExonEnd,m6AStart,m6AEnd,Probabilty
0,Cflar,chr1,+,58711559,58758884,58726436,58753922,58753783,58758884,58755655,58755656,0.009935
1,Cflar,chr1,+,58711559,58758884,58726436,58753922,58753783,58758884,58756334,58756335,0.007617
2,Cflar,chr1,+,58711559,58758884,58726436,58753922,58753783,58758884,58755721,58755722,0.006566
3,Cflar,chr1,+,58711559,58758884,58726436,58753922,58753783,58758884,58756882,58756883,0.006543
4,Cflar,chr1,+,58711559,58758884,58726436,58753922,58753783,58758884,58756911,58756912,0.006486
...,...,...,...,...,...,...,...,...,...,...,...,...
96004,Prdx3,chr19,-,60864050,60874556,60864665,60874467,60864050,60864719,60864565,60864566,0.001247
96005,Prdx3,chr19,-,60864050,60874556,60864665,60874467,60864050,60864719,60864357,60864358,0.001233
96006,Prdx3,chr19,-,60864050,60874556,60864665,60874467,60864050,60864719,60864703,60864704,0.000572
96007,Prdx3,chr19,-,60864050,60874556,60864665,60874467,60864050,60864719,60864440,60864441,0.000206
96008,Prdx3,chr19,-,60864050,60874556,60864665,60874467,60864050,60864719,60864054,60864055,0.000002

In [28]:
Overlap["LastExonStart"] = Overlap["LastExonStart"].astype(int)
Overlap["LastExonEnd"] = Overlap["LastExonEnd"].astype(int)

In [29]:
Positive = Overlap[Overlap["strand"]=="+"]
Positive = Positive.reset_index(drop = True)

In [30]:
Negative = Overlap[Overlap["strand"]=="-"]
Negative = Negative.reset_index(drop = True)

### Select m6A sites in the Coding region of LastExon

In [31]:
Positive = Positive[(Positive["m6AStart"] < Positive["cdsEnd"])&(Positive["m6AStart"] > Positive["LastExonStart"])]

In [32]:
Positive

,name,chrom,strand,txStart,txEnd,cdsStart,cdsEnd,LastExonStart,LastExonEnd,m6AStart,m6AEnd,Probabilty
8,Cflar,chr1,+,58711559,58758884,58726436,58753922,58753783,58758884,58753839,58753840,0.005613
16,Cflar,chr1,+,58711559,58758884,58726436,58753922,58753783,58758884,58753900,58753901,0.002519
100,Lmx1a,chr1,+,167689556,167848741,167689774,167846761,167846600,167848741,167846660,167846661,0.005565
102,Lmx1a,chr1,+,167689556,167848741,167689774,167846761,167846600,167848741,167846720,167846721,0.003107
103,Lmx1a,chr1,+,167689556,167848741,167689774,167846761,167846600,167848741,167846651,167846652,0.002561
...,...,...,...,...,...,...,...,...,...,...,...,...
49015,Pnliprp1,chr19,+,58728886,58744169,58729124,58744128,58744046,58744169,58744051,58744052,0.000250
49016,Pnliprp1,chr19,+,58728886,58744169,58729124,58744128,58744046,58744169,58744081,58744082,0.000216
49017,Pnliprp1,chr19,+,58728886,58744169,58729124,58744128,58744046,58744169,58744110,58744111,0.000087
49018,Pnliprp1,chr19,+,58728886,58744169,58729124,58744128,58744046,58744169,58744117,58744118,0.000041
49020,Pnliprp2,chr19,+,58759722,58777533,58759788,58777481,58777417,58777533,58777422,58777423,0.000273

In [33]:
Negative = Negative[(Negative["m6AStart"] > Negative["cdsStart"])&(Negative["m6AStart"] < Negative["LastExonEnd"])]

In [34]:
Negative

,name,chrom,strand,txStart,txEnd,cdsStart,cdsEnd,LastExonStart,LastExonEnd,m6AStart,m6AEnd,Probabilty
3,Dnah7a,chr1,-,53397005,53706761,53397106,53706692,53397005,53397313,53397118,53397119,0.008240
4,Dnah7a,chr1,-,53397005,53706761,53397106,53706692,53397005,53397313,53397243,53397244,0.008008
7,Dnah7a,chr1,-,53397005,53706761,53397106,53706692,53397005,53397313,53397284,53397285,0.005387
8,Dnah7a,chr1,-,53397005,53706761,53397106,53706692,53397005,53397313,53397271,53397272,0.004821
11,Dock10,chr1,-,80501072,80758448,80501706,80758448,80501072,80501826,80501753,80501754,0.005947
...,...,...,...,...,...,...,...,...,...,...,...,...
46963,1700019N19Rik,chr19,-,58785802,58794461,58785995,58794398,58785802,58786126,58786120,58786121,0.000021
46965,Vax1,chr19,-,59166186,59170056,59166186,59170029,59166186,59166774,59166392,59166393,0.002460
46969,Fam204a,chr19,-,60198585,60226697,60199435,60221296,60198585,60199487,60199451,60199452,0.001576
46972,Fam204a,chr19,-,60198585,60226697,60199435,60221296,60198585,60199487,60199461,60199462,0.000390
46984,Prdx3,chr19,-,60864050,60874556,60864665,60874467,60864050,60864719,60864703,60864704,0.000572

In [35]:
Data = Positive.append(Negative)
Data = Data.reset_index(drop = True)

In [36]:
Data

,name,chrom,strand,txStart,txEnd,cdsStart,cdsEnd,LastExonStart,LastExonEnd,m6AStart,m6AEnd,Probabilty
0,Cflar,chr1,+,58711559,58758884,58726436,58753922,58753783,58758884,58753839,58753840,0.005613
1,Cflar,chr1,+,58711559,58758884,58726436,58753922,58753783,58758884,58753900,58753901,0.002519
2,Lmx1a,chr1,+,167689556,167848741,167689774,167846761,167846600,167848741,167846660,167846661,0.005565
3,Lmx1a,chr1,+,167689556,167848741,167689774,167846761,167846600,167848741,167846720,167846721,0.003107
4,Lmx1a,chr1,+,167689556,167848741,167689774,167846761,167846600,167848741,167846651,167846652,0.002561
...,...,...,...,...,...,...,...,...,...,...,...,...
14259,1700019N19Rik,chr19,-,58785802,58794461,58785995,58794398,58785802,58786126,58786120,58786121,0.000021
14260,Vax1,chr19,-,59166186,59170056,59166186,59170029,59166186,59166774,59166392,59166393,0.002460
14261,Fam204a,chr19,-,60198585,60226697,60199435,60221296,60198585,60199487,60199451,60199452,0.001576
14262,Fam204a,chr19,-,60198585,60226697,60199435,60221296,60198585,60199487,60199461,60199462,0.000390
14263,Prdx3,chr19,-,60864050,60874556,60864665,60874467,60864050,60864719,60864703,60864704,0.000572

In [37]:
Data.to_csv("CodonEnumeration.csv", index=0)

### Create Bed

In [38]:
Bed = Data.iloc[:, [1, 3, 4]]

In [39]:
Bed.to_csv("CodonEnumeration.bed", sep="\t", header=False, index=False)

In [40]:
!bedtools getfasta -bed CodonEnumeration.bed -fi /pod/2/ke-lab/LUOZ/Reference/Fasta/mm10/mm10.fa -fo CodonEnumeration.txt